kind: Prometheus
apiVersion: monitoring.coreos.com/v1
metadata: 
  name: example
spec: 
  serviceMonitorSelector:
    matchLabels:
      propogated: "true"
    matchExpressions:
      - {key: tier, operator: In, values: [cache]}
  serviceAccountName: prometheus