kind: Pushgateway
apiVersion: monitoring.coreos.com/v1alpha1
metadata: 
  name: example
spec:
  prometheus:
    name: example
  replicas: 1
  serviceMonitorOverrides:
    metadataOverrides: 
      name: no-override
      labels:
        override: "true"
    endpointOverrides:
      honorLabels: false #not overriden
      honorTimestamps: false #not overriden
      interval: 1m #overriden
      scrapeTimeout: 30s