# permissions for end users to view pushgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pushgateway-viewer-role
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - pushgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - pushgateways/status
  verbs:
  - get
