# permissions for end users to edit pushgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pushgateway-editor-role
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - pushgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - pushgateways/status
  verbs:
  - get
