
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pushgateway-operator-2-manager-role
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - pushgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - pushgateways/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - pushgateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - update
  - create
  - list
  - patch
  - watch
  - delete
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - update
  - create
  - list
  - patch
  - watch
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - update
  - create
  - list
  - patch
  - watch
  - delete
- apiGroups:
  - 'batch'
  resources:
  - jobs
  verbs:
  - get
  - update
  - list
  - patch
  - watch
  - create
  - delete